export interface Financeiro {
    id?: number,
    usuarioId: string,
    fornecedores: string,
    nomeProd: string,
    nomeMarca: string,
    receita_despesa: boolean,
    provisao: boolean,
    nNota: string,
    valorUn: Number,
    Quantidade: Number,
    valorTotal: Number,
    dNegociacao: string,
    dVencimento: string,
    historico: string,
    conta: string,
    titulo: string,
    parcelado: string,
    nParcela: string,
    natureza: string,
    centro: string,
    baixado: boolean,
    dtBaixa: string
}